

export default [
        {
        label:'账号管理',
        to:'',
        children:[
                        {
                label:'管理员账号管理',
                to:'/admin/admins',
            },
                        {
                label:'管理员账号添加',
                to:'/admin/adminsadd',
            },
                        {
                label:'注册用户管理',
                to:'/admin/yonghu',
            },
                        {
                label:'添加新用户',
                to:'/admin/yonghuadd',
            },
                        {
                label:'密码修改',
                to:'/admin/mod',
            },
                    ]
    },
        {
        label:'地区管理',
        to:'',
        children:[
                        {
                label:'地区添加',
                to:'/admin/diquadd',
            },
                        {
                label:'地区查询',
                to:'/admin/diqu',
            },
                    ]
    },
        {
        label:'景点信息管理',
        to:'',
        children:[
                        {
                label:'景点信息添加',
                to:'/admin/jingdianxinxiadd',
            },
                        {
                label:'景点信息查询',
                to:'/admin/jingdianxinxi',
            },
                    ]
    },
        {
        label:'地方美食管理',
        to:'',
        children:[
                        {
                label:'美食分类添加',
                to:'/admin/meishifenleiadd',
            },
                        {
                label:'美食分类查询',
                to:'/admin/meishifenlei',
            },
                        {
                label:'地方美食添加',
                to:'/admin/difangmeishiadd',
            },
                        {
                label:'地方美食查询',
                to:'/admin/difangmeishi',
            },
                    ]
    },
        {
        label:'旅游线路管理',
        to:'',
        children:[
                        {
                label:'旅游线路添加',
                to:'/admin/lvyouxianluadd',
            },
                        {
                label:'旅游线路查询',
                to:'/admin/lvyouxianlu',
            },
                    ]
    },
        {
        label:'订单信息管理',
        to:'',
        children:[
                        {
                label:'预定查询',
                to:'/admin/yuding',
            },
                    ]
    },
        {
        label:'新闻管理',
        to:'',
        children:[
                        {
                label:'分类添加',
                to:'/admin/xinwenfenleiadd',
            },
                        {
                label:'分类查询',
                to:'/admin/xinwenfenlei',
            },
                        {
                label:'新闻添加',
                to:'/admin/xinwenxinxiadd',
            },
                        {
                label:'新闻查询',
                to:'/admin/xinwenxinxi',
            },
                    ]
    },
        {
        label:'系统管理',
        to:'',
        children:[
                        {
                label:'友情链接添加',
                to:'/admin/youqinglianjieadd',
            },
                        {
                label:'友情链接查询',
                to:'/admin/youqinglianjie',
            },
                        {
                label:'轮播图添加',
                to:'/admin/lunbotuadd',
            },
                        {
                label:'轮播图查询',
                to:'/admin/lunbotu',
            },
                        {
                label:'留言管理',
                to:'/admin/liuyanban',
            },
                    ]
    },
    ]
